-- CreateTable
CREATE TABLE "leads" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "companyName" TEXT NOT NULL,
    "responsibleName" TEXT NOT NULL,
    "segment" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "website" TEXT,
    "instagram" TEXT,
    "facebook" TEXT,
    "whatsappBusiness" TEXT NOT NULL,
    "employeeCount" TEXT NOT NULL,
    "companyStage" TEXT NOT NULL,
    "channels" TEXT NOT NULL,
    "marketingResponsible" TEXT NOT NULL,
    "postFrequency" TEXT NOT NULL,
    "adsInvestment" TEXT NOT NULL,
    "objectives" TEXT NOT NULL,
    "successDefinition" TEXT,
    "challenges" TEXT NOT NULL,
    "selfProfessionalism" INTEGER NOT NULL,
    "selfClarity" INTEGER NOT NULL,
    "selfDifferentiation" INTEGER NOT NULL,
    "selfSalesConversion" INTEGER NOT NULL,
    "selfStrategy" INTEGER NOT NULL,
    "contactName" TEXT NOT NULL,
    "contactEmail" TEXT NOT NULL,
    "contactPhone" TEXT NOT NULL,
    "consent" BOOLEAN NOT NULL DEFAULT false,
    "scoreGeneral" INTEGER NOT NULL,
    "scorePositioning" INTEGER NOT NULL,
    "scoreCommunication" INTEGER NOT NULL,
    "scoreDigitalPresence" INTEGER NOT NULL,
    "scoreContent" INTEGER NOT NULL,
    "scoreConversion" INTEGER NOT NULL,
    "scoreStrategy" INTEGER NOT NULL,
    "classification" TEXT NOT NULL,
    "priorities" TEXT NOT NULL,
    "recommendations" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'NOVO',

    CONSTRAINT "leads_pkey" PRIMARY KEY ("id")
);
